# Homework 2

2.  
 $$a. Gini = 1 - \sum_{i=0}^n p_i^2  = 1 - \frac{10^2} {20^2} + \frac{10^2} {20^2} = 1 - \frac{100 + 100} {400} = \frac {1} {2}$$
 $$b. Gini = 1 - \sum_{i=0}^n p_i^2  = 1 - \frac{1^2} {20^2} + \frac{1^2} {20^2}+ ... +\frac{1^2} {20^2} = 1 - \frac {1} {20} = \frac{19} {20}$$
 $$c. Gini = 1 - \sum_{i=0}^n p_i^2  = 1 - \frac{1^2} {20^2} + \frac{1^2} {20^2}+ ... +\frac{1^2} {20^2} = 1 - \frac {1} {20} = \frac{19} {20}$$
3. 7
5. b
6. t
7. r



In [19]:
exercise_3 = {"a1": [1,1,1,0,0,0,0,1,0], "a2": [1,1,0,0,1,1,0,0,1],
              "a3":[1.0,6.0,5.0,4.0,7.0,3.0,8.0,7.0,5.0], "Target":["+","+","-","+","-","-","-","+","-"]}
pd_exr_3 = pd.DataFrame(data=exercise_3)
pd_exr_3.describe()
pd_pos_class = pd_exr_3[pd_exr_3["Target"] == "+"]
pd_neg_class = pd_exr_3[pd_exr_3["Target"] == "-"]
count_poss = np.square(pd_pos_class["Target"].count()/pd_exr_3["Target"].count())
count_negs = np.square(pd_neg_class["Target"].count()/pd_exr_3["Target"].count())
gini = 1 - (count_poss + count_negs)
print(gini)

0.49382716049382713
0.49382716049382713


In [31]:
exercise_3 = {"Cust ID": [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20],
              "Gender": ["M","M","M","M","M","M","F","F","F","F","M","M","M","M","F","F","F","F","F","F"], 
              "Car Type": ["Family","Sports","Sports","Sports","Sports","Sports","Sports","Sports","Sports","Luxury","Family","Family","Family","Luxury","Luxury","Luxury","Luxury","Luxury","Luxury","Luxury"],
              "Shirt Size":["Small","Medium","Medium","Large","Extra Large","Extra Large","Small","Small","Medium","Large","Large","Extra Large","Medium","Extra Large","Small","Small","Medium","Medium","Medium","Large"],
              "Target":["C0","C0","C0","C0","C0","C0","C0","C0","C0","C0","C1","C1","C1","C1","C1","C1","C1","C1","C1","C1"]}
pd_exr_3 = pd.DataFrame(data=exercise_3)

pd_pos_class = pd_exr_3[pd_exr_3["Target"] == "C0"]
pd_neg_class = pd_exr_3[pd_exr_3["Target"] == "C1"]
count_poss = np.square(pd_pos_class["Target"].count()/pd_exr_3["Target"].count())
count_negs = np.square(pd_neg_class["Target"].count()/pd_exr_3["Target"].count())
gini = 1 - (count_poss + count_negs)
print(gini)
pd_exr_3.describe()

0.5


Cust ID
count  20.00000
mean   10.50000
std     5.91608
min     1.00000
25%     5.75000
50%    10.50000
75%    15.25000
max    20.00000

In [80]:
def my_gini(panda, col):
    grouping = panda.groupby(col)[col]
    prob_array = grouping.count()/panda[col].count()
    p = 0
    names = []
    for name, _ in grouping:
        names.append(name)
    for i in range(len(prob_array)):
        p+=np.square(prob_array[names[i]])
    gini = 1 - p
    return gini
print(my_gini(pd_exr_3, "Cust ID"))
print(my_gini(pd_exr_3, "Gender"))


0.95
0.5


In [2]:
import numpy as np
import pandas as pd
from scipy import stats

from sklearn.datasets import load_iris

from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz

from sklearn import model_selection
from sklearn import metrics

from sklearn.impute import SimpleImputer
from sklearn.decomposition import PCA

import matplotlib.pyplot as plt

%matplotlib inline

## Problem 1
*****

Load the iris sample dataset from sklearn **loadiris()** into Python using a Pandas dataframe.  Induce a set of binary Decision Trees with a minimum of 2 instances in the leaves, no splits of subsets below 5, and an maximal tree depth from 1 to 5 (you can leave the majority parameter to 95%).  Which depth values result in the highest Recall? Why? Which value resulted in the lowest Precision? Why?  Which value results in the best F1 score?  Explain the difference between the micro/macro/weighted methods of score calculation.

In [3]:
iris = load_iris()
pd_iris = pd.DataFrame(data = np.c_[iris.data, iris.target], columns = iris.feature_names+['species'])

pd_iris.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)     species  
count        150.000000  150.000000  
mean           1.199333    1.000000  
std            0.762238    0.819232  
min            0.100000    0.000000  
25%            0.300000    0.000000  
50%            1.300000    1.000000  
75%            1.800000    2.000000  
max            2.500000    2.000000

In [4]:
data_train, data_test, target_train, target_test = model_selection.train_test_split(iris.data,
                                                                    iris.target,
                                                                    test_size=0.2)

In [5]:
for i in range(5):
    predicted = DecisionTreeClassifier(max_depth = (i+1), min_samples_leaf = 2, min_samples_split = 5).fit(data_train, target_train).predict(data_test)
    print("----------------------------Tree with depth: " + str(i+1)+" -----------------------\n")
    print(metrics.classification_report(target_test,
                                    predicted))
    print("----------------------------Confusion Matrix---------------------------\n")
    print(metrics.confusion_matrix(target_test,
                               predicted))
    print()

----------------------------Tree with depth: 1 -----------------------

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       0.37      1.00      0.54         7
           2       0.00      0.00      0.00        12

   micro avg       0.60      0.60      0.60        30
   macro avg       0.46      0.67      0.51        30
weighted avg       0.45      0.60      0.49        30

----------------------------Confusion Matrix---------------------------

[[11  0  0]
 [ 0  7  0]
 [ 0 12  0]]

----------------------------Tree with depth: 2 -----------------------

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00         7
           2       1.00      1.00      1.00        12

   micro avg       1.00      1.00      1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00     

/home/mahmoud/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


## Problem 2
***
Load the **Breast Cancer Wisconsin (Diagnostic)** sample dataset from the **UCI Machine Learning Repository** (The discrete version at: **breast-cancer-wisconsin.data**)  into Python using  a  Pandas  dataframe.   Induce  a  binary Decision Tree with a minimum of 2 instances in the leaves, no splits of subsets below 5, and a maximal tree depth of 2 (use the default Gini criterion). Calculate the  Entropy,  Gini,  and  Misclassification  Error  of  the  first  split  -  what  is  the Information  Gain?   What  is  the  feature  selected  for  the  first  split,  and  what value determines the decision boundary?

In [6]:
breast = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data", header=None)
breast.columns=["Sample code number","Clump Thickness", "Uniformity of Cell Size", "Uniformity of Cell Shape", 
                "Marginal Adhesion", "Single Epithelial Cell Size","Bare Nuclei", "Bland Chromatin", 
                "Normal Nucleoli", "Mitoses", "Class:"]
breast_pd = breast.drop(columns=["Sample code number"])
nan_breast_pd = breast_pd.replace(to_replace="?",value=0)
nan_breast_pd.isna().sum() #All the nan values are in Bare Nuclei column

Clump Thickness                0
Uniformity of Cell Size        0
Uniformity of Cell Shape       0
Marginal Adhesion              0
Single Epithelial Cell Size    0
Bare Nuclei                    0
Bland Chromatin                0
Normal Nucleoli                0
Mitoses                        0
Class:                         0
dtype: int64

In [7]:
nan_breast_pd.describe()

Clump Thickness  Uniformity of Cell Size  Uniformity of Cell Shape  \
count       699.000000               699.000000                699.000000   
mean          4.417740                 3.134478                  3.207439   
std           2.815741                 3.051459                  2.971913   
min           1.000000                 1.000000                  1.000000   
25%           2.000000                 1.000000                  1.000000   
50%           4.000000                 1.000000                  1.000000   
75%           6.000000                 5.000000                  5.000000   
max          10.000000                10.000000                 10.000000   

       Marginal Adhesion  Single Epithelial Cell Size  Bland Chromatin  \
count         699.000000                   699.000000       699.000000   
mean            2.806867                     3.216023         3.437768   
std             2.855379                     2.214300         2.438364   
min             1.000000                     1.000000         1.000000   
25%             1.000000                     2.000000         2.000000   
50%             1.000000                     2.000000         3.000000   
75%             4.000000                     4.000000         5.000000   
max            10.000000                    10.000000        10.000000   

       Normal Nucleoli     Mitoses      Class:  
count       699.000000  699.000000  699.000000  
mean          2.866953    1.589413    2.689557  
std           3.053634    1.715078    0.951273  
min           1.000000    1.000000    2.000000  
25%           1.000000    1.000000    2.000000  
50%           1.000000    1.000000    2.000000  
75%           4.000000    1.000000    4.000000  
max          10.000000   10.000000    4.000000

In [8]:
breast_tree = DecisionTreeClassifier(max_depth = 2, min_samples_leaf = 2, min_samples_split = 5)
fitted_breast = breast_tree.fit(nan_breast_pd.drop(columns=["Class:","Bare Nuclei"]), nan_breast_pd["Class:"])
nan_breast_pd.columns[fitted_breast.tree_.feature] #Order of splits

Index(['Uniformity of Cell Size', 'Bland Chromatin', 'Mitoses', 'Mitoses',
       'Uniformity of Cell Shape', 'Mitoses', 'Mitoses'],
      dtype='object')

In [9]:
fitted_breast.feature_importances_

array([0.        , 0.88020446, 0.07898489, 0.        , 0.        ,
       0.        , 0.04081065, 0.        ])

In [10]:
nan_breast_pd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 10 columns):
Clump Thickness                699 non-null int64
Uniformity of Cell Size        699 non-null int64
Uniformity of Cell Shape       699 non-null int64
Marginal Adhesion              699 non-null int64
Single Epithelial Cell Size    699 non-null int64
Bare Nuclei                    699 non-null object
Bland Chromatin                699 non-null int64
Normal Nucleoli                699 non-null int64
Mitoses                        699 non-null int64
Class:                         699 non-null int64
dtypes: int64(9), object(1)
memory usage: 54.7+ KB


In [11]:
nan_breast_pd["Bare Nuclei"] = nan_breast_pd["Bare Nuclei"].astype(np.float64)
nan_breast_pd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 10 columns):
Clump Thickness                699 non-null int64
Uniformity of Cell Size        699 non-null int64
Uniformity of Cell Shape       699 non-null int64
Marginal Adhesion              699 non-null int64
Single Epithelial Cell Size    699 non-null int64
Bare Nuclei                    699 non-null float64
Bland Chromatin                699 non-null int64
Normal Nucleoli                699 non-null int64
Mitoses                        699 non-null int64
Class:                         699 non-null int64
dtypes: float64(1), int64(9)
memory usage: 54.7 KB


In [12]:
imp_breast_pd = nan_breast_pd
imp_breast_pd.columns = nan_breast_pd.columns
imp_breast_pd.isna().sum()

Clump Thickness                0
Uniformity of Cell Size        0
Uniformity of Cell Shape       0
Marginal Adhesion              0
Single Epithelial Cell Size    0
Bare Nuclei                    0
Bland Chromatin                0
Normal Nucleoli                0
Mitoses                        0
Class:                         0
dtype: int64

In [13]:
new_fitted_breast = breast_tree.fit(imp_breast_pd.drop(columns=["Class:"]), nan_breast_pd["Class:"])
imp_breast_pd.columns[new_fitted_breast.tree_.feature]

Index(['Uniformity of Cell Size', 'Bare Nuclei', 'Mitoses', 'Mitoses',
       'Uniformity of Cell Shape', 'Mitoses', 'Mitoses'],
      dtype='object')

In [14]:
new_fitted_breast.feature_importances_

array([0.        , 0.87550059, 0.07856279, 0.        , 0.        ,
       0.04593662, 0.        , 0.        , 0.        ])

In [15]:
new_fitted_breast.tree_.threshold

array([ 2.5,  5.5, -2. , -2. ,  2.5, -2. , -2. ])

In [16]:
index_right = new_fitted_breast.tree_.children_right[0] #4
new_fitted_breast.tree_.impurity[index_right]


0.2575857338820302

In [17]:
index_left = new_fitted_breast.tree_.children_left[0] # 1
new_fitted_breast.tree_.impurity[index_left]

0.05437918724632007

In [18]:
tresh = new_fitted_breast.tree_.threshold[0]
print(tresh)
f1 = imp_breast_pd.columns[new_fitted_breast.tree_.feature[0]]

print(f1)

2.5
Uniformity of Cell Size


In [19]:
rightchild = imp_breast_pd[imp_breast_pd[f1] > tresh]

In [20]:
rightchild.describe()

Clump Thickness  Uniformity of Cell Size  Uniformity of Cell Shape  \
count       270.000000               270.000000                270.000000   
mean          6.766667                 6.359259                  6.214815   
std           2.576921                 2.646560                  2.708613   
min           1.000000                 3.000000                  1.000000   
25%           5.000000                 4.000000                  4.000000   
50%           7.000000                 6.000000                  6.000000   
75%           9.000000                 9.000000                  8.000000   
max          10.000000                10.000000                 10.000000   

       Marginal Adhesion  Single Epithelial Cell Size  Bare Nuclei  \
count         270.000000                   270.000000   270.000000   
mean            5.211111                     5.074074     6.840741   
std             3.246369                     2.468025     3.606145   
min             1.000000                     2.000000     0.000000   
25%             2.000000                     3.000000     3.000000   
50%             5.000000                     5.000000     9.000000   
75%             8.000000                     6.000000    10.000000   
max            10.000000                    10.000000    10.000000   

       Bland Chromatin  Normal Nucleoli     Mitoses      Class:  
count       270.000000       270.000000  270.000000  270.000000  
mean          5.600000         5.514815    2.418519    3.696296  
std           2.442499         3.404262    2.462890    0.719087  
min           1.000000         1.000000    1.000000    2.000000  
25%           3.000000         3.000000    1.000000    4.000000  
50%           6.000000         5.000000    1.000000    4.000000  
75%           7.000000         9.000000    3.000000    4.000000  
max          10.000000        10.000000   10.000000    4.000000

In [21]:
leftchild = imp_breast_pd[imp_breast_pd[f1] <= tresh]

In [22]:
leftchild.describe()

Clump Thickness  Uniformity of Cell Size  Uniformity of Cell Shape  \
count       429.000000               429.000000                429.000000   
mean          2.939394                 1.104895                  1.314685   
std           1.756446                 0.306776                  0.704653   
min           1.000000                 1.000000                  1.000000   
25%           1.000000                 1.000000                  1.000000   
50%           3.000000                 1.000000                  1.000000   
75%           4.000000                 1.000000                  1.000000   
max          10.000000                 2.000000                  4.000000   

       Marginal Adhesion  Single Epithelial Cell Size  Bare Nuclei  \
count         429.000000                   429.000000   429.000000   
mean            1.293706                     2.046620     1.337995   
std             0.855156                     0.786967     1.311337   
min             1.000000                     1.000000     0.000000   
25%             1.000000                     2.000000     1.000000   
50%             1.000000                     2.000000     1.000000   
75%             1.000000                     2.000000     1.000000   
max            10.000000                    10.000000    10.000000   

       Bland Chromatin  Normal Nucleoli     Mitoses      Class:  
count       429.000000       429.000000  429.000000  429.000000  
mean          2.076923         1.200466    1.067599    2.055944  
std           1.068300         0.846598    0.527380    0.330170  
min           1.000000         1.000000    1.000000    2.000000  
25%           1.000000         1.000000    1.000000    2.000000  
50%           2.000000         1.000000    1.000000    2.000000  
75%           3.000000         1.000000    1.000000    2.000000  
max           7.000000        10.000000    8.000000    4.000000

In [23]:
left_tot = leftchild["Class:"].count()
left_c1 = leftchild[leftchild["Class:"] == 2].count()["Class:"]
left_c2 = leftchild[leftchild["Class:"] == 4].count()["Class:"]
left_p = [left_c1/left_tot, left_c2/left_tot]
ent = 0
gini = 0
for i in range(len(left_p)):
    ent += -left_p[i]*np.log2(left_p[i])
    gini += left_p[i]**2
gini= 1 - gini

print("Entropy for left child is", ent)
print("Gini for left child is", gini)
print("Classification error for left child is", 1-max(left_p))

Entropy for left child is 0.18411742692826688
Gini for left child is 0.05437918724632018
Classification error for left child is 0.027972027972028024


In [24]:
right_tot = rightchild["Class:"].count()
right_c1 = rightchild[rightchild["Class:"] == 2].count()["Class:"]
right_c2 = rightchild[rightchild["Class:"] == 4].count()["Class:"]
right_p = [right_c1/right_tot, right_c2/right_tot]
ent1 = 0
gini1 = 0
for j in range(len(right_p)):
    ent1 += -right_p[j]*np.log2(right_p[j])
    gini1 += right_p[j]**2
gini1= 1 - gini1

print("Entropy for left child is", ent1)
print("Gini for left child is", gini1)
print("Classification error for left child is", 1-max(right_p))

Entropy for left child is 0.6144552279266028
Gini for left child is 0.2575857338820302
Classification error for left child is 0.1518518518518519


## Problem 3
Load the **Breast Cancer Wisconsin (Diagnostic)** sample dataset from the **UCI Machine  Learning  Repository**  (The continuous version  at: **wdbc.data**)  into Python using  a  Pandas  dataframe.   Induce  the  same  binary  Decision  Tree as above (now using the continuous data) but perform a PCA dimensionality reduction beforehand.  Using only the first principal component of the data for a model fit, what is the F1, Precision, and Recall of the PCA-based single factor model compared to the original (continuous) data?  Repeat using the first and second principal components.  Using the Confusion Matrix, what are the values for  FP  and  TP  as  well  as  FPR/TPR?  Is  using  continuous  data  in  this  case beneficial within the model?  How?

In [29]:
cont_breast_pd = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data", header=None)
#cont_breast_pd.columns = ["ID", "Diagnosis",radius","texture", "perimeter", "area", "smoothness","compactness",
 #                         "concavity","concave points","symmetry","fractal dimension"]

In [30]:
cont_breast_pd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
0     569 non-null int64
1     569 non-null object
2     569 non-null float64
3     569 non-null float64
4     569 non-null float64
5     569 non-null float64
6     569 non-null float64
7     569 non-null float64
8     569 non-null float64
9     569 non-null float64
10    569 non-null float64
11    569 non-null float64
12    569 non-null float64
13    569 non-null float64
14    569 non-null float64
15    569 non-null float64
16    569 non-null float64
17    569 non-null float64
18    569 non-null float64
19    569 non-null float64
20    569 non-null float64
21    569 non-null float64
22    569 non-null float64
23    569 non-null float64
24    569 non-null float64
25    569 non-null float64
26    569 non-null float64
27    569 non-null float64
28    569 non-null float64
29    569 non-null float64
30    569 non-null float64
31    569 non-null float64
dtypes: float64(30), int64(1), obj

In [38]:
data_cont_breast_pd = cont_breast_pd.drop(columns=[0,1])
data_cont_breast_pd.describe()

2           3           4            5           6   \
count  569.000000  569.000000  569.000000   569.000000  569.000000   
mean    14.127292   19.289649   91.969033   654.889104    0.096360   
std      3.524049    4.301036   24.298981   351.914129    0.014064   
min      6.981000    9.710000   43.790000   143.500000    0.052630   
25%     11.700000   16.170000   75.170000   420.300000    0.086370   
50%     13.370000   18.840000   86.240000   551.100000    0.095870   
75%     15.780000   21.800000  104.100000   782.700000    0.105300   
max     28.110000   39.280000  188.500000  2501.000000    0.163400   

               7           8           9           10          11     ...      \
count  569.000000  569.000000  569.000000  569.000000  569.000000     ...       
mean     0.104341    0.088799    0.048919    0.181162    0.062798     ...       
std      0.052813    0.079720    0.038803    0.027414    0.007060     ...       
min      0.019380    0.000000    0.000000    0.106000    0.049960     ...       
25%      0.064920    0.029560    0.020310    0.161900    0.057700     ...       
50%      0.092630    0.061540    0.033500    0.179200    0.061540     ...       
75%      0.130400    0.130700    0.074000    0.195700    0.066120     ...       
max      0.345400    0.426800    0.201200    0.304000    0.097440     ...       

               22          23          24           25          26  \
count  569.000000  569.000000  569.000000   569.000000  569.000000   
mean    16.269190   25.677223  107.261213   880.583128    0.132369   
std      4.833242    6.146258   33.602542   569.356993    0.022832   
min      7.930000   12.020000   50.410000   185.200000    0.071170   
25%     13.010000   21.080000   84.110000   515.300000    0.116600   
50%     14.970000   25.410000   97.660000   686.500000    0.131300   
75%     18.790000   29.720000  125.400000  1084.000000    0.146000   
max     36.040000   49.540000  251.200000  4254.000000    0.222600   

               27          28          29          30          31  
count  569.000000  569.000000  569.000000  569.000000  569.000000  
mean     0.254265    0.272188    0.114606    0.290076    0.083946  
std      0.157336    0.208624    0.065732    0.061867    0.018061  
min      0.027290    0.000000    0.000000    0.156500    0.055040  
25%      0.147200    0.114500    0.064930    0.250400    0.071460  
50%      0.211900    0.226700    0.099930    0.282200    0.080040  
75%      0.339100    0.382900    0.161400    0.317900    0.092080  
max      1.058000    1.252000    0.291000    0.663800    0.207500  

[8 rows x 30 columns]

In [47]:
pca_breast = PCA()
fitted_pca = pca_breast.fit(data_cont_breast_pd)
pca_breast_percent_var = np.around(pca_breast.explained_variance_ratio_, 6)
for i in range(len(pca_breast_percent_var)):
    print(pca_breast_percent_var[i]*100, pca_breast_percent_var[i])

98.2045 0.982045
1.6176 0.016176
0.1558 0.001558
0.0121 0.000121
0.0088 8.8e-05
0.0007 7e-06
0.00039999999999999996 4e-06
9.999999999999999e-05 1e-06
0.0 0.0
0.0 0.0
0.0 0.0
0.0 0.0
0.0 0.0
0.0 0.0
0.0 0.0
0.0 0.0
0.0 0.0
0.0 0.0
0.0 0.0
0.0 0.0
0.0 0.0
0.0 0.0
0.0 0.0
0.0 0.0
0.0 0.0
0.0 0.0
0.0 0.0
0.0 0.0
0.0 0.0
0.0 0.0


In [72]:
first_pca_breast = PCA(n_components =1)
first_pca_comp = first_pca_breast.fit_transform(data_cont_breast_pd)
first_pca_breast.explained_variance_ratio_

array([0.98204467])

In [79]:
first_pca_comp.mean()

-3.8361815189016306e-14

In [81]:
breast_x, breast_x_test, breast_y, breast_y_test = model_selection.train_test_split(first_pca_comp,
                                                                    cont_breast_pd[1],
                                                                    test_size=0.2)
dt_breast = DecisionTreeClassifier(max_depth = 2, min_samples_leaf = 2,min_samples_split = 5).fit(breast_x, breast_y)


#print("----------------------------Tree with depth classification-----------------------\n")
print(metrics.classification_report(breast_y_test, dt_breast.predict(breast_x_test)))
#print("----------------------------Confusion Matrix---------------------------\n")
print(metrics.confusion_matrix(breast_y_test,dt_breast.predict(breast_x_test)))


              precision    recall  f1-score   support

           B       0.95      0.96      0.95        73
           M       0.93      0.90      0.91        41

   micro avg       0.94      0.94      0.94       114
   macro avg       0.94      0.93      0.93       114
weighted avg       0.94      0.94      0.94       114

[[70  3]
 [ 4 37]]


In [85]:
train_data, test_data, train_target, test_target = model_selection.train_test_split(data_cont_breast_pd,
                                                                    cont_breast_pd[1],
                                                                    test_size=0.2)
dt_cont_breast = DecisionTreeClassifier(max_depth = 2, min_samples_leaf = 2,min_samples_split = 5).fit(train_data, train_target)


#print("----------------------------Tree with depth classification-----------------------\n")
print(metrics.classification_report(test_target, dt_cont_breast.predict(test_data)))
#print("----------------------------Confusion Matrix---------------------------\n")
print(metrics.confusion_matrix(test_target,dt_cont_breast.predict(test_data)))

              precision    recall  f1-score   support

           B       0.90      0.94      0.92        67
           M       0.91      0.85      0.88        47

   micro avg       0.90      0.90      0.90       114
   macro avg       0.90      0.90      0.90       114
weighted avg       0.90      0.90      0.90       114

[[63  4]
 [ 7 40]]


In [86]:
two_pca_breast = PCA(n_components =2)
two_pca_comp = two_pca_breast.fit_transform(data_cont_breast_pd)
two_pca_breast.explained_variance_ratio_

array([0.98204467, 0.01617649])

In [113]:
two_pca_comp

array([[1160.1425737 , -293.91754364],
       [1269.12244319,   15.63018184],
       [ 995.79388896,   39.15674324],
       ...,
       [ 314.50175618,   47.55352518],
       [1124.85811531,   34.12922497],
       [-771.52762188,  -88.64310636]])

In [114]:
train2_data, test2_data, train2_target, test2_target = model_selection.train_test_split(two_pca_comp,
                                                                    cont_breast_pd[1],
                                                                    test_size=0.2)
dt_cont_breast = DecisionTreeClassifier(max_depth = 2, min_samples_leaf = 2,
                                        min_samples_split = 5).fit(train2_data, train2_target)


#print("----------------------------Tree with depth classification-----------------------\n")
print(metrics.classification_report(test2_target, dt_cont_breast.predict(test2_data)))
#print("----------------------------Confusion Matrix---------------------------\n")
print(metrics.confusion_matrix(test2_target,dt_cont_breast.predict(test2_data)))

              precision    recall  f1-score   support

           B       0.87      0.99      0.92        74
           M       0.97      0.72      0.83        40

   micro avg       0.89      0.89      0.89       114
   macro avg       0.92      0.86      0.88       114
weighted avg       0.90      0.89      0.89       114

[[73  1]
 [11 29]]


## Problem 4
Simulate a binary classification dataset with a single feature using a mixture of normal distributions with NumPy(Hint:  Generate two data frames with the random  number  and  a  class  label,  and  combine  them  together).   The  normal distribution  parameters  **np.random.normal**  should  be  (5,2)  and  (-5,2)  for the pair of samples.  Induce a binary Decision Tree of maximum depth 2, and obtain the threshold value for the feature in the first split.  How does this value compare to the empirical distribution of the feature?

In [22]:
import random



In [48]:
np.random.seed(267) #267
rand_data_1 = np.random.normal(5,2,500 )
rand_data_2 = np.random.normal(-5, 2, 1000-500)
class_1 = np.repeat("c1", 500)
class_2 = np.repeat("c2", 1000-500)
pd_1 = pd.DataFrame(dict(zip(['f1','Class'],[rand_data_1,class_1])))
pd_2 = pd.DataFrame(dict(zip(['f1','Class'],[rand_data_2,class_2])))
rand_data_frame = pd.concat([pd_1,pd_2])
rand_data_frame.describe()

f1
count  1000.000000
mean     -0.002313
std       5.293827
min     -10.353750
25%      -4.923400
50%      -0.061132
75%       4.857598
max       9.926335

In [49]:
rand_data_frame["f1"].var()

28.024599768152704

In [50]:
dt_rand = DecisionTreeClassifier(max_depth = 2).fit(rand_data_frame.drop(columns=["Class"]), rand_data_frame["Class"])
dt_rand.tree_.threshold

array([-0.48002306, -0.90108308, -2.        , -2.        ,  0.72923988,
       -2.        , -2.        ])

In [51]:
rand_data_frame.columns[dt_rand.tree_.feature]

Index(['f1', 'f1', 'f1', 'f1', 'f1', 'f1', 'f1'], dtype='object')

In [52]:
rand_data_frame.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 0 to 499
Data columns (total 2 columns):
f1       1000 non-null float64
Class    1000 non-null object
dtypes: float64(1), object(1)
memory usage: 23.4+ KB


In [56]:
rand_data_frame[rand_data_frame["Class"] == "c1"].min()

f1      -0.846103
Class          c1
dtype: object

In [58]:
rand_data_frame[rand_data_frame["Class"] == "c2"].max()

f1       0.728319
Class          c2
dtype: object